<?php

/**
 * Implementation of hook_feeds_plugins().
 */
function dla_catalog_feeds_plugins() {
  $info = array();

  $info['DLACatalogNodeProcessor'] = array(
    'name' => 'DLA Catalog Node Processor',
    'description' => 'Creates nodes from a parsed DLA Catalog CSV file.',
    'handler' => array(
      'parent' => 'FeedsNodeProcessor',
      'class' => 'DLACatalogNodeProcessor',
      'file' => 'DLACatalogNodeProcessor.inc',
      'path' => drupal_get_path('module', 'dla_catalog') . '/feeds',
    ),
  );

  return $info;

  }


/**
 * Implementation of hook_feeds_enable().
 */
function dla_catalog_enable() {

  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

?>